application: gocamp-2015
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: present/static
  application_readable: true
- url: /(.*\.(ico))$
  static_files: present/static/\1
  upload: present/static/.*\.(ico)
  application_readable: true
- url: /.*
  script: _go_app